export const GET_DEPLOYMENTS_REQUEST = "GET_DEPLOYMENTS_REQUEST";
export const GET_DEPLOYMENTS_SUCCESS = "GET_DEPLOYMENTS_SUCCESS";
export const GET_DEPLOYMENTS_FAIL = "GET_DEPLOYMENTS_FAIL";

export const CREATE_DEPLOYMENT_REQUEST = "CREATE_DEPLOYMENT_REQUEST";
export const CREATE_DEPLOYMENT_SUCCESS = "CREATE_DEPLOYMENT_SUCCESS";
export const CREATE_DEPLOYMENT_FAIL = "CREATE_DEPLOYMENT_FAIL";
