export const GET_OFFICERS_REQUEST = "GET_OFFICERS_REQUEST";
export const GET_OFFICERS_SUCCESS = "GET_OFFICERS_SUCCESS";
export const GET_OFFICERS_FAIL = "GET_OFFICERS_FAIL";


// Get single officer
export const GET_OFFICER_REQUEST = "GET_OFFICER_REQUEST";
export const GET_OFFICER_SUCCESS = "GET_OFFICER_SUCCESS";
export const GET_OFFICER_FAIL = "GET_OFFICER_FAIL";

// Create officer
export const CREATE_OFFICER_REQUEST = "CREATE_OFFICER_REQUEST";
export const CREATE_OFFICER_SUCCESS = "CREATE_OFFICER_SUCCESS";
export const CREATE_OFFICER_FAIL = "CREATE_OFFICER_FAIL";